version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=retMaybe
      - POSTGRES_PASSWORD=retMaybe
      - POSTGRES_DB=retMaybe
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doggr"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    hostname: backend
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=retMaybe
      - DB_USER=retMaybe
      - DB_PASS=retMaybe
      - PORT=8080
      - HOST=0.0.0.0
      - NODE_ENV=development
      - AUTH_SECRET=supersecret219340818092358
      - AUTH_DOMAIN=dev-2dtmb35dmkdjhb8l.us.auth0.com
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    hostname: frontend
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "5173:80"
    environment:
      - API_HOST=localhost
      - PORT=8080
      - AUTH_DOMAIN="dev-2dtmb35dmkdjhb8l.us.auth0.com"
      - AUTH_CLIENT="WTp4p0IS7rLzxWnDrIE9HJVEpsXwU3Uh"
      - AUTH_AUD="https://dev-2dtmb35dmkdjhb8l.us.auth0.com/api/v2/"
      - AUTH_SCOPE="openid profile email"
      - AUTH_REDIRECT="http://localhost:89/"
      - AUTH_EMAIL_KEY="http://localhost:5173/email"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db:
    driver: local
